language: scala
scala: 2.13.3
# os: linux-ppc64le
arch: ppc64le
dist: focal
jdk: default-jdk
script:
   - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test
   - cat $jvm-opts
   - cat $sbt-opts
   - cat $JVM_OPTS
   - cat $SBT_OPTS
   - echo $jvmopts
   - echo $sbtopts
   - cat $jvmopts
   - cat $sbtopts
