language: scala
scala: 2.13.3
arch: 
   - amd64
dist: focal
script:
#    - sudo mkdir -p /etc/sbt/
#    - sudo touch /etc/sbt/jvmopts
#    - sudo ls -l /etc/sbt/*
   - sbt ++$TRAVIS_SCALA_VERSION -v -XX:+UnlockExperimentalVMOptionsc -XX:+UseJVMCICompiler test
