language: scala
os: linux
arch: ppc64le
dist: focal

scala:
   - 2.10.4
   - 2.12.13

script:
  - sbt -jvm-opts -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler ... compile
  - sbt -jvm-opts -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler ... test
