language: scala
os: linux
arch: ppc64le
dist: focal
jdk: openjdk11

scala:
   - 2.10.4
   - 2.12.13

script:
  - sbt -jvm-opts travis/jvmopts.compile ... compile
  - sbt -jvm-opts travis/jvmopts.test ... test
